- pipeline.id: mssql-to-kafka
  path.config: "/usr/share/logstash/pipeline/logstash.conf"
  pipeline.workers: 1
- pipeline.id: consume-kafka
  path.config: "/usr/share/logstash/pipeline/consumer.conf"
  #queue.type: persisted